#!/bin/bash

# This script generates the cabal build files for this project from templates
# using bash, make and the C preprocessor.
#
# This file has the same terms for use and distribution as other files
# in this software. See file LICENSE for details.

set -euE -o pipefail
shopt -s failglob globstar

function create_makefile {
    echo '%.cabal: %.cabal.in ; @echo Generating "$@" ; cpp -nostdinc -E -P "$<" -o "$@"'

    for file in **/*.cabal.in
    do
        if [ ! -f "${file}" ]; then
            echo "${file} is not a regular file, skipping." >&2
            continue
        fi
        dest="${file%.in}"
        cpp -nostdinc "${file}" -M -MQ "${dest}"
    done
}

root_dir="$(realpath "$(dirname "${0}")")"
cd "${root_dir}"
create_makefile | make -f -
